packages:
  - packages/*

ignoredBuiltDependencies:
  - better-sqlite3
  - core-js-pure
  - cos-js-sdk-v5
  - esbuild
  - sharp
  - unrs-resolver

patchedDependencies:
  '@tencent-ai/agent-sdk@0.3.68': patches/@tencent-ai__agent-sdk@0.3.68.patch
