import type { TeacherDashboardData } from './types'

export const teacherDashboardDemo: TeacherDashboardData = {
  institutionName: '星河青少年创新中心',
  teacherName: '林老师',
  classes: [
    {
      id: 'creative-2a',
      name: '二年级创作 A 班',
      studentCount: 24,
      courseTitle: 'AI 太空海报创作营',
      progress: 42,
      completionRate: 88,
    },
    {
      id: 'game-4b',
      name: '四年级游戏 B 班',
      studentCount: 20,
      courseTitle: '弹跳球游戏设计',
      progress: 58,
      completionRate: 76,
    },
  ],
  lessons: [
    { id: 'space-poster-01', title: '认识会创作的小宝', courseTitle: 'AI 太空海报创作营' },
    { id: 'space-poster-02', title: '设计未来校园', courseTitle: 'AI 太空海报创作营' },
    { id: 'space-poster-03', title: '让太空校园海报动起来', courseTitle: 'AI 太空海报创作营' },
    { id: 'space-poster-04', title: '发布我们的太空展览', courseTitle: 'AI 太空海报创作营' },
    { id: 'bounce-game-01', title: '让小球跳起来', courseTitle: '弹跳球游戏设计' },
    { id: 'bounce-game-02', title: '给弹跳球加上得分规则', courseTitle: '弹跳球游戏设计' },
    { id: 'bounce-game-03', title: '设计不同难度的关卡', courseTitle: '弹跳球游戏设计' },
    { id: 'bounce-game-04', title: '举办班级游戏挑战赛', courseTitle: '弹跳球游戏设计' },
  ],
  courses: [
    {
      id: 'space-poster',
      title: 'AI 太空海报创作营',
      description: '用 AI 创作一张会动的未来校园太空海报。',
      coverAsset: '/xiaobao/xiaobao-art.png',
      stage: 'lower_primary',
      topic: 'AI 创作',
      status: 'ready',
      lessonCount: 4,
      completion: 42,
      assignedClassIds: ['creative-2a'],
      ageRange: '7-9 岁',
      goals: ['认识 AI 创作工具', '完成一张动态太空海报'],
      expectedOutcome: '每位学生完成一张可展示的未来校园动态海报。',
      chapters: [
        {
          id: 'space-poster-chapter-1',
          title: '灵感与设计',
          order: 1,
          lessons: [
            {
              id: 'space-poster-01',
              title: '认识会创作的小宝',
              durationMinutes: 45,
              completion: 100,
              objectives: ['认识文字和图片都能帮助表达创意'],
              steps: ['和小宝对话收集太空校园灵感', '选出最喜欢的创意'],
              teacherTips: ['鼓励学生用自己的语言描述画面'],
              resources: [{ id: 'space-poster-01-slides', title: '太空灵感卡', type: 'slides', status: 'ready' }],
              assignment: '画出未来校园的一处特别设计。',
              capabilities: ['chat', 'image'],
              skills: ['idea-explorer'],
              mcpServers: ['safe-image-library'],
            },
            {
              id: 'space-poster-02',
              title: '设计未来校园',
              durationMinutes: 45,
              completion: 100,
              objectives: ['用提示词描述太空校园'],
              steps: ['写下画面关键词', '生成并调整校园主画面'],
              teacherTips: ['提醒学生保留最能表达主题的元素'],
              resources: [
                { id: 'space-poster-02-worksheet', title: '提示词设计单', type: 'worksheet', status: 'ready' },
              ],
              assignment: '完善海报中的人物和建筑。',
              capabilities: ['chat', 'image'],
              skills: ['poster-designer'],
              mcpServers: ['safe-image-library'],
            },
          ],
        },
        {
          id: 'space-poster-chapter-2',
          title: '制作与发布',
          order: 2,
          lessons: [
            {
              id: 'space-poster-03',
              title: '让太空校园海报动起来',
              durationMinutes: 45,
              completion: 0,
              objectives: ['为海报设计一个动态效果'],
              steps: ['选择要动起来的画面元素', '生成动态海报并预览'],
              teacherTips: ['先完成一个简单动作，再尝试更多变化'],
              resources: [{ id: 'space-poster-03-demo', title: '动态海报示例', type: 'demo', status: 'ready' }],
              assignment: '完成一张至少有一个动态效果的海报。',
              capabilities: ['chat', 'image', 'video'],
              skills: ['poster-designer', 'motion-maker'],
              mcpServers: ['safe-image-library', 'video-studio'],
            },
            {
              id: 'space-poster-04',
              title: '发布我们的太空展览',
              durationMinutes: 45,
              completion: 0,
              objectives: ['介绍作品的创作想法'],
              steps: ['整理作品说明', '布置班级太空展览'],
              teacherTips: ['让每位学生用一句话介绍自己的作品'],
              resources: [
                { id: 'space-poster-04-assignment', title: '展览讲解卡', type: 'assignment', status: 'planned' },
              ],
              assignment: '准备一段 30 秒作品介绍。',
              capabilities: ['chat', 'image', 'video'],
              skills: ['presentation-coach'],
              mcpServers: [],
            },
          ],
        },
      ],
    },
    {
      id: 'bounce-game',
      title: '弹跳球游戏设计',
      description: '从一个会跳的小球开始设计自己的闯关游戏。',
      coverAsset: '/xiaobao/xiaobao-coding.png',
      stage: 'upper_primary',
      topic: '创意编程',
      status: 'draft',
      lessonCount: 4,
      completion: 58,
      assignedClassIds: ['game-4b'],
      ageRange: '9-11 岁',
      goals: ['理解游戏规则与反馈', '完成一个可玩的弹跳球游戏'],
      expectedOutcome: '每位学生完成一个有计分规则的弹跳球游戏。',
      chapters: [
        {
          id: 'bounce-game-chapter-1',
          title: '游戏原型',
          order: 1,
          lessons: [
            {
              id: 'bounce-game-01',
              title: '让小球跳起来',
              durationMinutes: 45,
              completion: 100,
              objectives: ['让角色响应点击和碰撞'],
              steps: ['创建小球角色', '添加弹跳动作'],
              teacherTips: ['先让一个动作稳定运行'],
              resources: [{ id: 'bounce-game-01-demo', title: '弹跳动作示例', type: 'demo', status: 'ready' }],
              assignment: '调整小球的速度和颜色。',
              capabilities: ['chat', 'code'],
              skills: ['game-builder'],
              mcpServers: [],
            },
            {
              id: 'bounce-game-02',
              title: '给弹跳球加上得分规则',
              durationMinutes: 45,
              completion: 0,
              objectives: ['为游戏添加分数反馈'],
              steps: ['确定得分条件', '显示并测试分数'],
              teacherTips: ['让学生先写清楚得分规则'],
              resources: [{ id: 'bounce-game-02-worksheet', title: '得分规则表', type: 'worksheet', status: 'ready' }],
              assignment: '设计三种不同的得分方式。',
              capabilities: ['chat', 'code'],
              skills: ['game-builder'],
              mcpServers: [],
            },
          ],
        },
        {
          id: 'bounce-game-chapter-2',
          title: '挑战升级',
          order: 2,
          lessons: [
            {
              id: 'bounce-game-03',
              title: '设计不同难度的关卡',
              durationMinutes: 45,
              completion: 0,
              objectives: ['用规则区分游戏难度'],
              steps: ['增加障碍物', '调整关卡速度'],
              teacherTips: ['每次只改变一个规则再测试'],
              resources: [{ id: 'bounce-game-03-slides', title: '关卡设计提示', type: 'slides', status: 'planned' }],
              assignment: '完成一个进阶关卡。',
              capabilities: ['chat', 'code'],
              skills: ['game-builder'],
              mcpServers: [],
            },
            {
              id: 'bounce-game-04',
              title: '举办班级游戏挑战赛',
              durationMinutes: 45,
              completion: 0,
              objectives: ['收集同伴试玩反馈'],
              steps: ['邀请同学试玩', '记录并改进游戏'],
              teacherTips: ['引导学生把反馈变成一个具体改进'],
              resources: [
                { id: 'bounce-game-04-assignment', title: '试玩反馈单', type: 'assignment', status: 'planned' },
              ],
              assignment: '根据一条反馈改进游戏。',
              capabilities: ['chat', 'code'],
              skills: ['game-builder'],
              mcpServers: [],
            },
          ],
        },
      ],
    },
  ],
  todaySchedule: [
    { id: 'schedule-1', time: '09:30', classId: 'creative-2a', lessonId: 'space-poster-03', status: 'upcoming' },
    { id: 'schedule-2', time: '14:00', classId: 'game-4b', lessonId: 'bounce-game-02', status: 'upcoming' },
  ],
  pendingReviews: [
    { id: 'work-1', studentName: '陈小雨', title: '月球上的未来学校', type: '互动海报', submittedAt: '今天 08:42' },
    { id: 'work-2', studentName: '周星宇', title: '会变色的弹跳球', type: '网页游戏', submittedAt: '昨天 19:20' },
  ],
  works: [
    {
      id: 'work-1',
      studentName: '陈小雨',
      title: '月球上的未来学校',
      type: '互动海报',
      classId: 'creative-2a',
      courseTitle: 'AI 太空海报创作营',
      submittedAt: '今天 08:42',
      previewAsset: '/xiaobao/xiaobao-art.png',
      status: 'pending',
      featured: false,
    },
    {
      id: 'work-2',
      studentName: '周星宇',
      title: '会变色的弹跳球',
      type: '网页游戏',
      classId: 'game-4b',
      courseTitle: '弹跳球游戏设计',
      submittedAt: '昨天 19:20',
      previewAsset: '/xiaobao/xiaobao-coding.png',
      status: 'pending',
      featured: false,
    },
    {
      id: 'work-3',
      studentName: '林可欣',
      title: '太空植物观察站',
      type: '动态海报',
      classId: 'creative-2a',
      courseTitle: 'AI 太空海报创作营',
      submittedAt: '8月14日 16:30',
      previewAsset: '/xiaobao/xiaobao-science.png',
      status: 'reviewed',
      featured: true,
      rating: 'excellent',
      comment: '观察细致，画面故事很完整。',
    },
    {
      id: 'work-4',
      studentName: '赵一航',
      title: '彩虹弹跳挑战',
      type: '网页游戏',
      classId: 'game-4b',
      courseTitle: '弹跳球游戏设计',
      submittedAt: '8月14日 15:18',
      previewAsset: '/xiaobao/xiaobao-robotics.png',
      status: 'reviewed',
      featured: false,
      rating: 'good',
      comment: '规则清楚，可以继续丰富关卡变化。',
    },
  ],
  recentSessions: [
    {
      id: 'record-1',
      classId: 'game-4b',
      className: '四年级游戏 B 班',
      lessonId: 'bounce-game-01',
      lessonTitle: '设计第一关',
      startedAt: '2026-08-14T14:00:00+08:00',
      endedAt: '2026-08-14T14:48:00+08:00',
      durationMinutes: 48,
      studentCount: 20,
      pointLimit: 100,
      capabilities: ['chat', 'code'],
      skills: ['game-builder'],
      mcpServers: [],
    },
    {
      id: 'record-2',
      classId: 'creative-2a',
      className: '二年级创作 A 班',
      lessonId: 'space-poster-02',
      lessonTitle: '设计未来校园',
      startedAt: '2026-08-12T09:30:00+08:00',
      endedAt: '2026-08-12T10:15:00+08:00',
      durationMinutes: 45,
      studentCount: 24,
      pointLimit: 120,
      capabilities: ['chat', 'image'],
      skills: ['poster-designer'],
      mcpServers: ['safe-image-library'],
    },
    {
      id: 'record-3',
      classId: 'creative-2a',
      className: '二年级创作 A 班',
      lessonId: 'space-poster-01',
      lessonTitle: '认识会创作的小宝',
      startedAt: '2026-08-08T09:30:00+08:00',
      endedAt: '2026-08-08T10:17:00+08:00',
      durationMinutes: 47,
      studentCount: 24,
      pointLimit: 80,
      capabilities: ['chat', 'image'],
      skills: ['idea-explorer'],
      mcpServers: ['safe-image-library'],
    },
  ],
  activeSession: null,
  classDetails: [
    {
      summary: {
        id: 'creative-2a',
        name: '二年级创作 A 班',
        studentCount: 24,
        courseTitle: 'AI 太空海报创作营',
        progress: 42,
        completionRate: 88,
        status: 'active',
        nextLessonId: 'space-poster-03',
      },
      students: [
        {
          id: 'student-01',
          name: '陈小雨',
          status: 'creating',
          completedTasks: 5,
          totalTasks: 8,
          lastActiveAt: '今天 09:12',
        },
        {
          id: 'student-02',
          name: '周星宇',
          status: 'completed',
          completedTasks: 8,
          totalTasks: 8,
          lastActiveAt: '今天 08:55',
        },
        {
          id: 'student-03',
          name: '李可心',
          status: 'creating',
          completedTasks: 6,
          totalTasks: 8,
          lastActiveAt: '昨天 19:42',
        },
        {
          id: 'student-04',
          name: '王一诺',
          status: 'needs_attention',
          completedTasks: 3,
          totalTasks: 8,
          lastActiveAt: '8月13日',
        },
        {
          id: 'student-05',
          name: '赵晨曦',
          status: 'completed',
          completedTasks: 8,
          totalTasks: 8,
          lastActiveAt: '昨天 18:20',
        },
        {
          id: 'student-06',
          name: '孙乐乐',
          status: 'creating',
          completedTasks: 4,
          totalTasks: 8,
          lastActiveAt: '今天 09:05',
        },
      ],
      lessonProgress: [
        {
          lessonId: 'space-poster-01',
          title: '认识会创作的小宝',
          order: 1,
          status: 'completed',
          completedAt: '2026-08-08',
        },
        {
          lessonId: 'space-poster-02',
          title: '设计未来校园',
          order: 2,
          status: 'completed',
          completedAt: '2026-08-12',
        },
        { lessonId: 'space-poster-03', title: '让太空校园海报动起来', order: 3, status: 'next' },
        { lessonId: 'space-poster-04', title: '发布我们的太空展览', order: 4, status: 'locked' },
      ],
      recentSessions: [],
    },
    {
      summary: {
        id: 'game-4b',
        name: '四年级游戏 B 班',
        studentCount: 20,
        courseTitle: '弹跳球游戏设计',
        progress: 58,
        completionRate: 76,
        status: 'active',
        nextLessonId: 'bounce-game-02',
      },
      students: [
        {
          id: 'student-07',
          name: '张子墨',
          status: 'creating',
          completedTasks: 6,
          totalTasks: 10,
          lastActiveAt: '今天 10:02',
        },
        {
          id: 'student-08',
          name: '刘梓涵',
          status: 'completed',
          completedTasks: 10,
          totalTasks: 10,
          lastActiveAt: '昨天 20:10',
        },
        {
          id: 'student-09',
          name: '黄嘉树',
          status: 'creating',
          completedTasks: 7,
          totalTasks: 10,
          lastActiveAt: '今天 09:48',
        },
        {
          id: 'student-10',
          name: '吴思远',
          status: 'needs_attention',
          completedTasks: 4,
          totalTasks: 10,
          lastActiveAt: '8月12日',
        },
        {
          id: 'student-11',
          name: '郑欣怡',
          status: 'creating',
          completedTasks: 8,
          totalTasks: 10,
          lastActiveAt: '昨天 17:36',
        },
        {
          id: 'student-12',
          name: '林浩然',
          status: 'completed',
          completedTasks: 10,
          totalTasks: 10,
          lastActiveAt: '今天 08:31',
        },
      ],
      lessonProgress: [
        { lessonId: 'bounce-game-01', title: '让小球跳起来', order: 1, status: 'completed', completedAt: '2026-08-14' },
        { lessonId: 'bounce-game-02', title: '给弹跳球加上得分规则', order: 2, status: 'next' },
        { lessonId: 'bounce-game-03', title: '设计不同难度的关卡', order: 3, status: 'locked' },
        { lessonId: 'bounce-game-04', title: '举办班级游戏挑战赛', order: 4, status: 'locked' },
      ],
      recentSessions: [
        {
          id: 'record-1',
          classId: 'game-4b',
          className: '四年级游戏 B 班',
          lessonId: 'bounce-game-01',
          lessonTitle: '设计第一关',
          startedAt: '2026-08-14T14:00:00+08:00',
          endedAt: '2026-08-14T14:48:00+08:00',
          durationMinutes: 48,
          studentCount: 20,
          pointLimit: 100,
          capabilities: ['chat', 'code'],
          skills: ['game-builder'],
          mcpServers: [],
        },
      ],
    },
  ],
}
