import { describe, expect, it } from 'vitest'
import { decryptJWE, encryptJWE } from '../session'

describe('session JWE secret handling', () => {
  it('accepts 32-byte hex secrets generated by the desktop app', async () => {
    const secret = '0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef'
    const token = await encryptJWE({ userId: 'user_1' }, '1h', secret)
    await expect(decryptJWE<{ userId: string }>(token, secret)).resolves.toEqual({ userId: 'user_1' })
  })
})
